### ISSUE TITLE
"Update Available" banner showing in dashboard for offline devices when using ping

### ISSUE THREAD

**Issue by flacjacket** [esphome/issues#2650]
### The problem

When running esphome with `ESPHOME_DASHBOARD_USE_PING` as `"true"`, for devices with an update available that are also offline, the banner at the top of the device is decorated as a device needing an update (purple line with "Update Available" as the text in the upper right corner). When the ping setting is not used, the device correctly shows the offline status here instead (red line with "Offline" as the text in the upper right corner). In both cases, the purple "Update" button correctly shows in the bottom left corner.

Once the device has been updated, when it is taken offline, the device in the UI correctly moves between online and offline states.

### Which version of ESPHome has the issue?

2021.10.x

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

**Comment by flacjacket** [comment]
At some point between then and now (2022.2.5), this has been fixed, so now the top banner on the card shows offline and the "Update" button is present for offline, out-of-date devices.

**Comment by eloo** [comment]
@flacjacket just stumbled of this issue and unfortunately i need say this issue seems not to be fixed :( 

all my 4 offline devices (with old firmware) are shown the update but not the offline tag. 
so this issues is still unresolved for me

**Comment by flacjacket** [comment]
Interesting, I'm on the same version, and my offline device that needs to be updated is showing the correct "offline" banner.

**Comment by eloo** [comment]
hmm okay weird.. 
im running the esphome in a container (thats why i need ping) but can not see why this is happening.
unfortunately the dashboard is not providing any useful logs so i can debug it. 

maybe its possible to add some logs (debug level or so) for the pingthread? so its possible to see what the container is trying to ping and maybe some looks if a device is going to be marked as offline or online?
